apiVersion: v1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-10-11T12:13:10Z
  deletionGracePeriodSeconds: 30
  deletionTimestamp: 2018-10-11T12:17:55Z
  generateName: hs-depl-7cff47bb66-
  labels:
    app: haskserv
    pod-template-hash: "3799036622"
  name: hs-depl-7cff47bb66-t2hnf
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: hs-depl-7cff47bb66
    uid: 46c6bed5-cd4d-11e8-b2b5-10bf480b8490
  resourceVersion: "2880"
  selfLink: /api/v1/namespaces/default/pods/hs-depl-7cff47bb66-t2hnf
  uid: 04c97e60-cd4f-11e8-b2b5-10bf480b8490
spec:
  containers:
  - image: m282021/hsserv:no_port
    imagePullPolicy: IfNotPresent
    name: haskserv1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-gkkt9
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: mike-k53sk
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-gkkt9
    secret:
      defaultMode: 420
      secretName: default-token-gkkt9
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-10-11T12:13:10Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-10-11T12:13:12Z
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2018-10-11T12:13:10Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://5cb2d2e219f59f61c52a45072ff41424ea29ec29dcef8cb4ad29273aa8aad00d
    image: hsserv:latest
    imageID: docker://sha256:629c5714f08a813ed2617c9bda0694a1b552b3fe0da6706464d0087fb56fe744
    lastState: {}
    name: haskserv1
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-10-11T12:13:11Z
  hostIP: 192.168.2.54
  phase: Running
  podIP: 10.32.0.4
  qosClass: BestEffort
  startTime: 2018-10-11T12:13:10Z
