apiVersion: v1
kind: Service
metadata:
  name: haskserv-svc
  labels:
    app: haskserv
spec:
  type: NodePort
  externalIPs: [192.168.2.54]
  ports:
  - port: 3001
    targetPort: 3000
  selector:
    app: haskserv